# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java package with Maven
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.github/**'
      - '.idea/**'
      - '.settings/**'
      - '.vscode/**'
      - 'README*.md'
      - '.gitignore'
      - '.editorconfig'
      - '.gitattributes'
      - '.mergify.yml'
      - 'CHANGELOG.md'
      - 'CONTRIBUTORS.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'qodana.yaml'
      - 'SECURITY.md'
      - '.imgbotconfig'
  workflow_dispatch:
concurrency:
  # On master/release, we don't want any jobs cancelled so the sha is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  group: ${{ github.ref == 'refs/heads/master' }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  package:
    runs-on: ubuntu-latest
    needs: prepare
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Clean
        run: mvn --file pom.xml clean
      - name: Package
        run: |
          result_path=aftifact
          mkdir -p ${result_path}
          mvn --file pom.xml -DskipTests -Duser.name='Github Action' package
          cp target/fileserver.jar ${result_path}/fileserver.jar
          cp target/fileserver-javadoc.jar ${result_path}/fileserver-javadoc.jar
          cp target/fileserver-sources.jar ${result_path}/fileserver-sources.jar
          cp -r target/apidocs ${result_path}/apidocs
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fileserver
          path: |
            aftifact
      - name: Release resource
        run: |
          rm -r aftifact

