name: Mac OS Wrapper Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Java ${{ matrix.java }} Maven Wrapper
    runs-on: macos-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build Project
        run: ./mvnw -B clean package --file pom.xml
