name: Mac OS Wrapper Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Java ${{ matrix.java }} Maven Wrapper
    runs-on: macos-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build Project
        run: |
          mvn -N io.takari:maven:wrapper
          ./mvnw -B clean package
